Update pxyupdate

diff --git a/sys/pxyupdate b/sys/pxyupdate
--- a/sys/pxyupdate
+++ b/sys/pxyupdate
@@ -1,12 +1,31 @@
 #!/bin/bash
-cd $HOME/pxy
-mv $HOME/pxy/sys/exe/run/*.csv $HOME/pxy/sys/exe/run/_*.csv 
+
+dir=$HOME/pxy/sys/exe/run
+
+# Check if the script is in a Git repository
+if [ ! -d "$dir/.git" ]; then
+    echo "Error: This script must be run from within a Git repository."
+    exit 1
+fi
+
+# Move to the directory
+cd $HOME/pxy/sys/exe/run
+
+# Move all CSV files (including hidden files) to their temporary versions
+for file in *.csv _*.csv; do
+    mv "$file" "_$file"
+done
+
 echo '                                 '
 echo "       ******** GET UPDATES *******"
 echo '                                 '
+
+# Move to the Git repository directory
+cd $dir
+
 git fetch --all
 echo '                                 '
-echo "       ****** RESET SOFTWERE ******"
+echo "       ****** RESET SOFTWARE ******"
 echo '                                 '
 git reset --hard origin/main
 sudo cp ~/pxy/sys/pxy ~/pxy/sys/p
@@ -15,5 +34,11 @@ sudo chmod +x /usr/local/bin/*
 echo '                                 '
 echo "       ***** UPDATE COMPLETED *****"
 echo '                                 '
-#rm $HOME/pxy/sys/exe/run/filePnL.csv
-mv $HOME/pxy/sys/exe/run/_*.csv $HOME/pxy/sys/exe/run/*.csv
+
+# Move back to the original directory
+cd $HOME/pxy/sys/exe/run
+
+# Move back the temporary versions to their original names
+for file in _*.csv; do
+    mv "$file" "$(basename "$file" _)"
+done
