Update pxyupdate

diff --git a/sys/pxyupdate b/sys/pxyupdate
--- a/sys/pxyupdate
+++ b/sys/pxyupdate
@@ -2,6 +2,15 @@
 
 dir=$HOME/pxy/sys/exe/run
 
+# Check if the script is in a Git repository
+if [ ! -d "$dir/.git" ]; then
+    echo "Error: This script must be run from within a Git repository."
+    exit 1
+fi
+
+# Move back to the home directory
+cd $HOME
+
 # Move all CSV files to their temporary versions
 for file in $dir/*.csv; do
     mv "$file" "$dir/$(basename "$file" .csv)_temp.csv"
@@ -10,6 +19,10 @@ done
 echo '                                 '
 echo "       ******** GET UPDATES *******"
 echo '                                 '
+
+# Move to the Git repository directory
+cd $dir
+
 git fetch --all
 echo '                                 '
 echo "       ****** RESET SOFTWARE ******"
@@ -21,6 +34,9 @@ sudo chmod +x /usr/local/bin/*
 echo '                                 '
 echo "       ***** UPDATE COMPLETED *****"
 echo '                                 '
+
+# Move back to the original directory
+cd $HOME
 
 # Move back the temporary versions to their original names
 for file in $dir/*_temp.csv; do
